# Copyright redhat-consulting-services Authors
# SPDX-License-Identifier: Apache-2.0
---
- name: Label infra nodes
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars.yaml
  roles:
    - ../../../configure_nodes
