version: 3

images:
  base_image:
    name: registry.fedoraproject.org/fedora:44
    platform: linux/amd64

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

# Custom package manager path for the RHEL based images
options:
  package_manager_path: /usr/bin/dnf

additional_build_steps:
  prepend_base: |
    ARG OPENSHIFT_VERSION=4.19.5
    RUN dnf install -y unzip python3 python3-pip
    RUN pip3 install --upgrade ansible

    RUN curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}/openshift-install-linux.tar.gz && \
        tar -xzf openshift-install-linux.tar.gz --strip-components=0 -C /usr/local/bin openshift-install && \
        chmod +x /usr/local/bin/openshift-install

    RUN curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}/openshift-client-linux.tar.gz && \
        tar -xzf openshift-client-linux.tar.gz --strip-components=0 -C /usr/local/bin oc kubectl && \
        chmod +x /usr/local/bin/oc /usr/local/bin/kubectl

    RUN curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}/oc-mirror.tar.gz && \
        tar -xzf oc-mirror.tar.gz --strip-components=0 -C /usr/local/bin oc-mirror && \
        chmod +x /usr/local/bin/oc-mirror

    RUN rm -f *.tar.gz *.zip

  prepend_galaxy: |
    COPY ./collections /tmp/collections
