# Copyright redhat-consulting-services Authors
# SPDX-License-Identifier: Apache-2.0
---

- name: Create output directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '2775'
  loop:
    - "{{ oc_mirror_base_path }}/workspace"
    - "{{ oc_mirror_base_path }}/mirror"
    - "{{ oc_mirror_base_path }}/cache"
    - "{{ oc_mirror_base_path }}/credentials"
    - "{{ oc_mirror_base_path }}/image-sets"

- name: Check registry source and destination types are valid
  ansible.builtin.assert:
    that:
      - mirror.source.type in ['registry', 'disk']
      - mirror.destination.type in ['registry', 'disk']
    fail_msg: "Invalid source or destination type. Must be 'registry' or 'disk'."

- name: Check desination registry settings
  ansible.builtin.assert:
    that:
      - mirror.destination.type == 'registry' and mirror.destination.registry is not none
    fail_msg: "Destination registry is required for registry destination type"

- name: Check source registry settings
  ansible.builtin.assert:
    that:
      - mirror.source.type == 'registry' and mirror.source.auth_config is not none
    fail_msg: "Source registry auth_config is required for registry source type"

- name: Create image set configuration files
  ansible.builtin.template:
    src: image-set.yaml.j2
    dest: "{{ oc_mirror_base_path }}/image-sets/{{ item.name }}.yaml"
    mode: '0660'
  loop: "{{ image_sets }}"

- name: Create registry auth.json file for oc-mirror
  when: mirror.enabled | bool and (mirror.source.type == 'registry' or mirror.destination.type == 'registry')
  ansible.builtin.copy:
    content: '{{ (mirror.source.auth_config | default("{}") | from_json) | combine(mirror.destination.auth_config | default("{}") | from_json, recursive=True) }}'
    dest: "{{ oc_mirror_base_path }}/credentials/auth.json"
    mode: '0660'

- name: Execute oc-mirror to mirror images
  when: mirror.enabled | bool and item.enabled | default(false) | bool
  changed_when: true
  ansible.builtin.command: >
    {% if mirror.source.type == 'registry' and mirror.destination.type == 'disk' %}
    {# registry-to-disk #}
    oc-mirror \
      --v2 \
      --config {{ oc_mirror_base_path }}/image-sets/{{ item.name }}.yaml \
      --authfile {{ oc_mirror_base_path }}/credentials/auth.json \
      --log-level debug \
      --workspace file://{{ oc_mirror_base_path }}/workspace \
      --cache-dir {{ oc_mirror_base_path }}/cache \
      --src-tls-verify={{ mirror.source.tls_verify | default(true) }} \
      file://{{ oc_mirror_base_path }}/mirror/{{ item.destination }}
    {% endif %}

    {% if mirror.source.type == 'disk' and mirror.destination.type == 'registry' %}
    {# disk-to-registry #}
    oc-mirror \
      --v2 \
      --config {{ oc_mirror_base_path }}/image-sets/{{ item.name }}.yaml \
      --authfile {{ oc_mirror_base_path }}/credentials/auth.json \
      --from file://{{ oc_mirror_base_path }}/mirror/{{ item.destination }} \
      --dest-tls-verify={{ mirror.destination.tls_verify | default(true) }} \
      --log-level debug \
      --workspace file://{{ oc_mirror_base_path }}/workspace \
      --cache-dir {{ oc_mirror_base_path }}/cache \
      docker://{{ mirror.destination.registry }}{% if item.destination is defined and item.destination %}/{{ item.destination }}{% endif %}
    {% endif %}

    {% if mirror.source.type == 'registry' and mirror.destination.type == 'registry' %}
    {# registry-to-registry #}
    oc-mirror \
      --v2 \
      --config {{ oc_mirror_base_path }}/image-sets/{{ item.name }}.yaml \
      --authfile {{ oc_mirror_base_path }}/credentials/auth.json \
      --src-tls-verify={{ mirror.source.tls_verify | default(true) }} \
      --dest-tls-verify={{ mirror.destination.tls_verify | default(true) }} \
      --log-level debug \
      --workspace file://{{ oc_mirror_base_path }}/workspace \
      --cache-dir {{ oc_mirror_base_path }}/cache \
      docker://{{ mirror.destination.registry }}{% if item.destination is defined and item.destination %}/{{ item.destination }}{% endif %}
    {% endif %}
  loop: "{{ image_sets }}"
  register: oc_mirror_results

- name: Show output
  ansible.builtin.debug:
    msg: "{{ item.stdout }}"
  loop: "{{ oc_mirror_results.results | selectattr('stdout', 'defined') | list }}"
  loop_control:
    label: "{{ item.item.name }}"
