name: "🐛 Bug Report"
description: "Report a problem with the Ansible collection or execution environment."
title: "[BUG]: "
labels: ["bug"]
assignees: []
projects: ["redhat-consulting-services/1"]

body:
  - type: markdown
    attributes:
      value: |
        **Before submitting a bug report:**
        - Ensure you are using the latest version of the collection, role or execution environment.
        - Check existing issues for duplicates.

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Execution environment, Collection, Role, Other
      options:
        - Collection
        - Execution environment
        - Role
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: ansible_version
    attributes:
      label: "Ansible Version"
      description: "Which version of Ansible are you using?"
      placeholder: "e.g., 2.14"

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Describe the bug in detail."
      placeholder: "Eerror messages, unexpected behavior, etc."

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the bug."

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"

  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
