name: "✨ Feature Request"
description: "Suggest a new feature or improvement for the Ansible collection."
title: "[FEATURE] "
labels: ["feature request"]
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Execution environment, Collection, Role, Other
      options:
        - Collection
        - Execution environment
        - Role
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: feature
    attributes:
      label: "Feature Description"
      description: "Describe the feature you would like to see."
      placeholder: "e.g., Add support for mirroring additional operator catalogs"

  - type: textarea
    id: benefits
    attributes:
      label: "Benefits / Use Cases"
      description: "Explain why this feature would be useful."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternatives you've considered, if any."
