# Copyright redhat-consulting-services Authors
# SPDX-License-Identifier: Apache-2.0
---
- name: Mirror images from source to destination
  hosts: localhost
  gather_facts: false
  roles:
    - /opt/roles/mirror_images
