# Copyright redhat-consulting-services Authors
# SPDX-License-Identifier: Apache-2.0
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars.yaml
  roles:
    - ../../../configure-nodes
