# Copyright redhat-consulting-services Authors
# SPDX-License-Identifier: Apache-2.0
---

- name: Create output directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  loop:
    - "{{ oc_mirror_base_path }}/workdir"
    - "{{ oc_mirror_base_path }}/credentials"
    - "{{ oc_mirror_base_path }}/image-sets"

# TODO generate for each array entry a dedicated file
- name: Generate image set configuration files
  ansible.builtin.template:
    src: image-set-configuration.yaml.j2
    dest: "{{ oc_mirror_base_path }}/image-sets/image-sets.yaml"
    mode: '0644'

- name: Generate source registry authentication file
  when: mirror.enabled | bool and mirror.source.type == 'registry'
  ansible.builtin.template:
    src: plain.txt.j2
    dest: "{{ oc_mirror_base_path }}/credentials/source-config.json"
    mode: '0644'
  vars:
    config: "{{ mirror.source.auth_config }}"

- name: Generate destination registry authentication file
  when: mirror.enabled | bool and mirror.destination.type == 'registry'
  ansible.builtin.template:
    src: plain.txt.j2
    dest: "{{ oc_mirror_base_path }}/credentials/destination-config.json"
    mode: '0644'
  vars:
    config: "{{ mirror.destination.auth_config }}"
