# Copyright redhat-consulting-services Authors
# SPDX-License-Identifier: Apache-2.0
---

- name: Create output directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  loop:
    - "{{ oc_mirror_base_path }}/workdir"
    - "{{ oc_mirror_base_path }}/image-sets"

- name: Generate image set configuration files
  ansible.builtin.template:
    src: image-set-configuration.yaml.j2
    dest: "{{ oc_mirror_base_path }}/image-sets/image-sets.yaml"
    mode: '0644'
