name: Ansible Code Validation

on:
  push:
    branches:
      - main
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**.ansible-lint'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**.ansible-lint'

jobs:
  ansible-lint:
    uses: redhat-consulting-services/github-actions-collection/.github/workflows/ansible-lint.yaml@main
    permissions:
      contents: read
    with:
      exclude-paths: "examples"
      collections: "redhat_consulting_services.openshift dellemc.openmanage"

  integration-tests:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Ansible
        run: pip install ansible

      - name: Run bootstrap_cluster scenario tests
        run: roles/bootstrap_cluster/_tests/ci/run-tests.sh

      - name: Run add_nodes scenario tests
        run: roles/add_nodes/_tests/ci/run-tests.sh
